### ISSUE TITLE
collectstatic fail with ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by iXioN** [redouane/django-fontawesome#7]
when the django STATICFILES_STORAGE is set to 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage', the collect static fail because select2/select2.css refer to a non existing image: 'select2/select2x2.png'

here is the stack
```
Post-processed 'fontawesome/css/font-awesome.min.css' as 'fontawesome/css/font-awesome.min.04425bbdc624.css'
Post-processing 'fontawesome/select2/select2.css' failed!

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/myproject/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/myproject/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/myproject/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/.virtualenvs/myproject/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/myproject/local/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/vagrant/.virtualenvs/myproject/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle_noargs
    collected = self.collect()
  File "/home/vagrant/.virtualenvs/myproject/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 120, in collect
    raise processed
ValueError: The file 'fontawesome/select2/select2x2.png' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7f61e9c0e790>.
```

**Comment by redouane** [comment]
fixed in #8
